insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,2);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,6);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,30);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,58);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,31);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),1,32
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),2,38);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),2,67);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),2,68
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),3,25);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),3,26);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),3,71
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,2);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,3);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,4);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,5);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,37);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),4,55
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),5,27);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),5,65);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),5,90
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,9);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,11);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,49);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,60);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,87);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),6,94
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),7,86
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,76);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,77);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,78);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,79);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,80);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,81);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,82);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,83);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),8,84
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),9,42
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),10,125
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,95);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,96);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,97);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,98);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,99);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,100);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,101);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,102);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,103);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,104);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,105);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),11,106
);insert into mkt_app_permission_class_ref values(nextval('seq_app_permission'),12,73);